### ISSUE TITLE
Errors when running: npm run dev (step 4 in the readme)

### ISSUE THREAD

**Issue by houghtonweihu** [imoneoi/openchat-ui#7]
I was able to run: python -m ochat.serving.openai_api_server --model openchat/openchat-3.5-0106
I finished steps 1, 2, 3 in readme and when I tried step 4: npm run dev, I got the following:

> ai-chatbot-starter@0.1.0 dev
> next dev

openchat-ui/node_modules/next/dist/lib/picocolors.js:134
const { env, stdout } = ((_globalThis = globalThis) == null ? void 0 : _globalThis.process) ?? {};
                                                                                             ^
SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at Module.mod.require (openchat-ui/node_modules/next/dist/server/require-hook.js:64:28)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (openchat-ui/node_modules/next/dist/build/output/log.js:55:21)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
npm ERR! code 1
npm ERR! path /home/....../openchat-ui
npm ERR! command failed
npm ERR! command sh -c next dev

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/...../.npm/_logs/2024-01-15T13_59_35_379Z-debug.log

**Comment by sunbc0120** [comment]
upgrade node.js to the latest fixes it for me.
